### ISSUE TITLE
Demo doesn't work on opera

### ISSUE THREAD

**Issue by danielribeiro** [mauricemach/coffeekup#10]
The site http://coffeekup.org/ doesn't work on opera 10.53. Wonder if this will work on this browser at all....

**Comment by mauricemach** [comment]
The demo is based on Mozilla's Bespin/Skywriter and unfortunately only Firefox, Chrome and Safari support text rendering on canvas at the moment. If I can find the time later I'll add a plain textarea fallback to support IE and Opera though. If you want to fork it and tweak the site to just use the textarea if bespin is not available, I'd be glad to pull.

The lib on the other hand is by all means meant to work on Opera, and indeed the "regular" and "decaf" examples do. The "creme" example (using `<script type="text/coffeescript">`) was not working through. I managed to fix compilation of string templates in this context and it's already on master. Compiling templates in "live" code form inside "text/coffeescript" tags in opera does not seem possible though, the string values of functions are all messed up. But then, that CoffeeScript feature is not intended for serious use anyway.

Thanks for bringing this to my attention!
