### ISSUE TITLE
CoffeeScript is going to make "yield" the reserved word

### ISSUE THREAD

**Issue by sgtpep** [mauricemach/coffeekup#113]
So coffeekup-*.coffee doesn't compile with coffeescript from master rasing exception: "SyntaxError: reserved word "yield" on line 215".

**Comment by ghost** [comment]
there is a new fork of coffeekup called coffeecup because maurice is missing for a long time and we are working on the new fork. try this https://github.com/gradus/coffeecup
if there is any issues raise it there.

**Comment by sgtpep** [comment]
Oh, I see. I will take a look at it. Thank you!

**Comment by nonocast** [comment]
still error when using coffeecup
