### ISSUE TITLE
Incorrect package.json

### ISSUE THREAD

**Issue by evandrix** [mauricemach/coffeekup#117]
Hi,

While trying to install from /package.json, after cloning the git repo, the following warning was displayed:

npm WARN package.json fs-boot@0.0.9 'devDependences' should probably be 'devDependencies'

indicating a typo in this line of the file:

..." **devDependencies** ": {"jade": "0.13.0", "eco": "1.1.0-rc-1", "ejs": "0.4.3", "haml": "0.4.2"},...

**Comment by jeef3** [comment]
It's actally kriskowal/fs-boot#3. They haven't republished or bumped the version yet.

**Comment by krzysu** [comment]
so what should I do to install fs-boot@0.0.9 by npm? In my case looks like connect-livereload@0.1.4 depends on fs-boot@0.0.9 and I cannot proceed.

**Comment by jeef3** [comment]
I have the same problem, but have just been ignoring it. I don't think it's causing any issues?

​Until fs-boot is updated to 0.0.10...

**Comment by evandrix** [comment]
lost interest in writing CoffeeScript, so I'm closing this.
