### ISSUE TITLE
HR element is ignored if it has no attributes

### ISSUE THREAD

**Issue by edoloughlin** [mauricemach/coffeekup#12]
The code below only produces the second HR element.
    hr
    hr width:'100%'

**Comment by mauricemach** [comment]
An element in CoffeeKup is a function. When you write:

```
  hr width: '100%'
```

You're indirectly writing the following javascript:

```
  hr({width: '100%'});
```

If you want an empty tag, you need the following javascript:

```
  hr();
```

Which translated to coffeescript/coffeekup, is:

```
  hr()
```

**Comment by edoloughlin** [comment]
Oops, of course.
