### ISSUE TITLE
coffeekup breaks with coffeescript 1.0 becuase of changes made to OptionParser

### ISSUE THREAD

**Issue by idorosen** [mauricemach/coffeekup#14]
Works fine when changing process.argv to process.argv.slice 2 in coffeekup.coffee on line 39.

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
I have not experienced this yet. I'll post back if I run across it.

I suggest you make a pull-request to @mauricemach with your change.

**Comment by mauricemach** [comment]
Just released 0.2.2 with support for coffeescript 1.0!

**Comment by idorosen** [comment]
Thank you!

**Comment by jaekwon** [comment]
thank you from SF.
