### ISSUE TITLE
Helper bug: ck_repeat

### ISSUE THREAD

**Issue by ghost** [mauricemach/coffeekup#17]
Check helper in IE. As far as I can remember <code>Array(count).join(string)</code> different in different browsers:

<pre>
ck_repeat = function(string, count) {
  return Array(count + 1).join(string);
}; 
</pre>

**Comment by mauricemach** [comment]
Worked in IE8 and IE7 mode. Couldn't find anything about it on the web, do you have any additional info?

**Comment by ghost** [comment]
Hmm. It even works in ie6. Apparently I was wrong. IE evil, makes people paranoid :)

Sorry for the wrong issue.

**Comment by mauricemach** [comment]
No problem! :)
