### ISSUE TITLE
Howto mix tags and text?

### ISSUE THREAD

**Issue by phaer** [mauricemach/coffeekup#23]
Hi,
If i write

```
p ->
    "You can redistribute it and/or modify it under the terms of the "
    a href: "http://www.gnu.org/licenses/agpl-3.0.html", rel: "license", -> "GNU Affero General Public License"
    "."
```

I get

```
<p><a href="http://www.gnu.org/licenses/agpl-3.0.html" rel="license">GNU Affero General Public License</a>.</p>
```

As you can see, the first string gets lost somewhere. As inline links are a quite common thing, i wonder if there is a way to do this in coffescript?

thanks

**Comment by aeosynth** [comment]
You should really use markdown for that, but there is the `text` helper:
    p ->
        text "You can redistribute it and/or modify it under the terms of the "
        a href: "http://www.gnu.org/licenses/agpl-3.0.html", rel: "license", -> "GNU Affero General Public License"
        text "."

**Comment by focusaurus** [comment]
@aeosynth, can you elaborate on how or why markdown would be used here?

**Comment by aeosynth** [comment]
how - find a markdown module, add its parse method to the coffeekup template's context.

why - http://chriseppstein.github.com/blog/2010/02/08/haml-sucks-for-content/

**Comment by phaer** [comment]
Thanks for your fast response, I have been using the text helper successfully for the last 3 days. I see your point regarding markdown, but it's just a copyright notice not something i want to have an extra file for.
