### ISSUE TITLE
there's any way that use Express's helpers int coffekup?

### ISSUE THREAD

**Issue by arden** [mauricemach/coffeekup#24]
there's any way that use Express's helpers int coffekup?

**Comment by alduro** [comment]
same question here.
How can I use csrf helper in coffeekup template ?

**Comment by alduro** [comment]
any news ?

**Comment by mauricemach** [comment]
Deeply sorry for the late reply. Had some personal issues but now I'm back.

Probably doesn't matter to you anymore, but here's the answer. No, you couldn't in CK 0.2.3. In [0.2.4beta](https://github.com/mauricemach/coffeekup/tree/0.2.4beta), you can. Static and dynamic helpers will show up in your template as "context" variables, that is, attached to `@/this`. If you define a helper called foo, you can use it as `@foo`.
