### ISSUE TITLE
@body undefined in context

### ISSUE THREAD

**Issue by spielstein** [mauricemach/coffeekup#27]
Hi,
first of all, thanks for coffeekup!
I created a small express project with coffeekup templates. It works fine, except that @body is always undefined in the layout.coffee context.

I'm using express 1.0.7, coffeescript 1.0.1 and coffeekup 0.2.2

**Comment by ghost** [comment]
I believe the current version of coffeekup does not meet the new template engine guidelines specified here... http://expressjs.com/migrate.html#Template-Engine-Compliance

**Comment by spielstein** [comment]
Sorry, just saw I had activated express 2.0.0-pre. So this is obviously the cause for the problem; 1.0.7 works.
