### ISSUE TITLE
layout.coffee?

### ISSUE THREAD

**Issue by hackervera** [mauricemach/coffeekup#34]
Error: EBADF, Bad file descriptor '/Users/tyler/instantcoffee/views/layout.coffee'

why is it asking for layout.coffee?

**Comment by henrikh** [comment]
It's part of Express. Express will automatically use 'view/layout.coffee' as the layout file for a view. To avoid this, disable layouts for your views.

[View rendering in Express](http://expressjs.com/guide.html#view-rendering)

**Comment by hackervera** [comment]
Thanks!

## 

Tyler Gillies
Sent with Sparrow
