### ISSUE TITLE
precompilation to function: (locals) -> html

### ISSUE THREAD

**Issue by ghost** [mauricemach/coffeekup#4]
Hi! Good work. I like this philosophy.
I would like to use Coffeekup on clientside with Sammy framework, but precompiling coffekup templates on server to pure functions like in haml-js:
Haml(haml) -> template(locals) -> html.
Is it possible?

**Comment by mauricemach** [comment]
It is under way, I'm working on compiling the templates to standalone functions that don't depend on the rendering engine. It should be up in a few days.

Meanwhile, you can precompile your templates to JS (using any standard CoffeeScript precompilation scheme) and render them in the browser using only the 2k coffeekup.js (take a look at [this example](http://github.com/mauricemach/coffeekup/blob/master/examples/browser/decaf.html)).

**Comment by ghost** [comment]
Thanks for response.

**Comment by mauricemach** [comment]
Just pushed it to master. If you could help me test it, that would be great!

```
template = coffeekup.compile -> h1 @foo
```

...send `template.toString()` to browser and:

```
console.log template(context: {foo: 'bar'}, locals: {ping: 'pong'})
```
