### ISSUE TITLE
Named templates as tags?

### ISSUE THREAD

**Issue by dbrans** [mauricemach/coffeekup#42]
Hi there,
Can a template be named and used inside another template as a tag?
Thanks.

**Comment by mauricemach** [comment]
Sorry for the absurd delay.

In [0.2.4beta](https://github.com/mauricemach/coffeekup/tree/0.2.4beta), this will work:

```
ck = require 'coffeekup'

main = ->
  h1 'hi'
  username 'bob'

username = (n) ->
  div id: 'username', ->
    a href: "/users/#{n}", -> n

log ck.render main, hardcode: {username}
```

It will generate:

```
<h1>hi</h1><div id="username"><a href="/users/bob">bob</a></div>
```

Note that this will hardcode the stringified contents of `username` inside `main`, not pass it by reference.
