### ISSUE TITLE
CoffeeKup Syntax Highlighting

### ISSUE THREAD

**Issue by lconnell** [mauricemach/coffeekup#43]
I don't see any coffeekup specific syntax highlighters for any editor.  Are their any available? Sorry if this is wrong place to post this, didn't see anywhere else more appropriate.

Thanks

**Comment by mauricemach** [comment]
Hey lconnell,

CoffeeKup is actually CoffeeScript being used to express markup, so you can use any of [these](https://github.com/jashkenas/coffee-script/wiki/Text-editor-plugins).
