### ISSUE TITLE
Add to middlemanapp.com

### ISSUE THREAD

**Issue by mythz** [mauricemach/coffeekup#44]
Hi, I think CoffeeKup would make a nice addition to middlemanapp.com

I asked @middlemanapp and he said they support all languages supported by Tilt:
https://github.com/rtomayko/tilt

**Comment by mauricemach** [comment]
I'd love to see CoffeeKup tilt-compatible, I'm a huge fan of sinatra, but I guess the only way would be [through the coffeekup command](https://github.com/rtomayko/tilt/pull/36) and I don't know if performance would be acceptable for real usage.
