### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by mark-hahn** [mauricemach/coffeekup#45]
CK looks nice.  I'd really like to try it but I can't find docs anywhere. My google searches reached some discussion that mentions the docs.

Some help?

**Comment by kadirpekel** [comment]
Hi @mark-hahn,

Not every open source project becomes mature immediately, so they need some time, some attention and some contribution to grow hence much of them are not paid ones and developers have to survive for continuing their daily life in significant standarts.

Do you have sufficient docs? https://github.com/mark-hahn

So...

Would you mind reading the code, and give a fresh start for documentation by adding some if you like this project, want it to survive and want to show your appreciation.

Best.

**Comment by mark-hahn** [comment]
I'll be honest.  I read the code and I can't make heads nor tails of
it.  It takes the function source, adds a var for each tag used, and
then somehow magically something runs.  I have no idea how "html ->"
turns into "&lt;html&gt;" and I am a long-time coffeescript user.  I have no
doubt the code is awesome. I guess I could step through it with a
debugger.

I think maybe Maurice's writing style is incompatible with my
background.  There are a lot of references to things that aren't
defined. Who is Markaby?  The total amount of description other than
code is "Defining locals and context variables:" and "Precompiling to
functions:'.  Then it veers off into Zappa, Express and Meryl, which I
also am not familiar with.

I know how limited time and resources are for open-source.   However,
I am still left with the problem that I would really really like to
use CK and I haven't any idea where to start.  There must be others in
my shoes.

How did the current community learn CK?  Did everyone read the source
to figure it out?  These aren't rhetorical questions.  I'd really like
to know.  If there was a quick one-page tutorial starting with basics
and explaining what is going on, then I think it would attract a lot
of users.

P.S.  I would happily put more docs in my github project if someone
asked a question. I haven't had that problem though since no one
cares.  :-)

**Comment by mark-hahn** [comment]
I'll make everyone a deal.  If someone can give me a quick description of what CK does and how it works, I will then study it further and use it until I am proficient.  Then I will contribute a page of description aimed at idiots like me with no background in the area.   I like writing docs on a topic I like. Check out my project to see if you think my writing is good enough.

I'm serious about this. I promise not to renege.  If I do not follow up like I promise then everyone knows where I live: https://github.com/mark-hahn

**Comment by mark-hahn** [comment]
Sorry, I bumped the close button.

**Comment by kadirpekel** [comment]
lol :)

Personally your reasonings and deal not make sense for me :)

So my _humble_ suggestion is that don't ever ask for something in a harsh, unkind and unrhetorical way such 'Where are the docs?' for an open source project. Sorry if i hurt, but this is how i feel, that pushes me to respond you such above.

Best.

**Comment by mark-hahn** [comment]
> don't ever ask for something in a harsh, unkind and unrhetorical way such 'Where are the docs?'

I'm sorry for the misunderstanding.  When I asked the question I really did think there were docs I could not find.  I should have known it would come across as  "why does this stupid project not have any docs?".

I apologize for the weirdness of the whole thread.  I really want to use KC.  I guess I will sit down and spend the time to dissect the code to figure out what is going on. I may ask a few questions here.

**Comment by mauricemach** [comment]
@mark Reading this now it's amazing you ended up writing such a nice intro about CoffeeKup's internals. Thanks for sticking around!

I'm finally writing a reference for the CoffeeKup API and "syntax". The source on 0.2.4beta is also heavily annotated and the docco-generated HTML is at /docs (soon will be on the revised website). Sorry this wasn't all available when you first learned of the lib!

**Comment by kadirpekel** [comment]
@mauricemach @mark-hahn did a really nice job, well done! Also as reading this thread now, sorry if i had bumped an overdose reaction.

**Comment by mauricemach** [comment]
@kadirpekel what you said was true, but really a little over in the specific case of @mark-hahn, since he was not _demanding_ docs, he was just puzzled that some people where referencing something he couldn't find. But thanks for the good intention of making the point that we shouldn't demand anything from open source anyway.
