### ISSUE TITLE
How to do subroutines?

### ISSUE THREAD

**Issue by mark-hahn** [mauricemach/coffeekup#48]
I want to do something like this ...

```
labelAndInput = (lbl) -> 
    div lbl
    input type:text

template = ->
    div ->
        labelAndInput "hello"
        labelAndInput "world"
```

Everything I try is failing because of the lack of closure.  Maybe I've just gotten so used to closures I've forgotten how to program without them.  How do others accomplish this?

**Comment by mark-hahn** [comment]
I got a solution working.  I passed the labelAndInput function in as a local to template.  Since dynamic_locals was off the function was pasted in as text and used that way.

This had a problem though. No function "input" was created because it wasn't present in template, just in labelAndInput.  I had to patch coffeekup to scan all functions added as locals to find needed tags.

So this must not be the way everyone else does this or they would have had the same problem.  I would still like to know the right way to do this.

**Comment by mauricemach** [comment]
The solution you used was right. Pass it as a "hardcoded" local. In 0.2.4beta you do the same but in this format:

```
ck.render tpl, hardcode: {foo: -> 'bar'}
```

And it already does the same as your patch, it looks into locals to be hardcoded to find all the needed tags.
