### ISSUE TITLE
"coffeekup -w" quits on syntax error

### ISSUE THREAD

**Issue by bmidgley** [mauricemach/coffeekup#50]
this invocation should report the error and then go back into the watching state instead of bailing out completely. Some of us make syntax errors occasionally :)

**Comment by sveisvei** [comment]
occasionally :)

**Comment by mauricemach** [comment]
Sorry for the stupid bug! Fixed in [5fb9c390337e9867bb0e](https://github.com/mauricemach/coffeekup/commit/5fb9c390337e9867bb0e875384c31177ec013024).
