### ISSUE TITLE
Conditional form "<option selected='selected'>" near impossible.

### ISSUE THREAD

**Issue by randallb** [mauricemach/coffeekup#55]
I've tried countless ways to conditionally output "selected = 'selected'" in an option field. Not having any luck.

Tried:

option selected: "true" if @value is "value"
option selected: (if @value is "value" then "true" else "")
etc...

Any insight?

**Comment by mauricemach** [comment]
You could make it work with:

```
option selected: if @foo is 'bar' then 'selected' else ''
```

But I just pushed a fix to handle booleans specially, and now you can just do:

```
option selected: (@foo is 'bar')
```

**Comment by mauricemach** [comment]
Actually, in my first example, false would result in `<option selected=""></option>`.

In the second example, with the latest version, false is correctly rendered as `<option></option>`.

**Comment by randallb** [comment]
Awesome. Updating now.
