### ISSUE TITLE
Add support for compilation to JS in the coffeekup command.

### ISSUE THREAD

**Issue by mauricemach** [mauricemach/coffeekup#58]

**Comment by aaronshaf** [comment]
+1

I've been trying to figure out how the template.js file was compiled in the browser examples, assuming this could be done from the coffeekup command. Would love to see this supported.

**Comment by mauricemach** [comment]
@aaronshaf: the template.js was built by a task in the `Cakefile` that went with the examples. This task used `CoffeeKup.compile` directly.

Now in the released 0.3.0 "final" you can do that in the CLI with `coffeekup --js`. In the examples, the `Cakefile` was replaced by a little shell script that uses this command.

**Comment by aaronshaf** [comment]
@mauricemach, awesome, you rock! Thanks!
