### ISSUE TITLE
Word "input" prevents rendering.

### ISSUE THREAD

**Issue by randallb** [mauricemach/coffeekup#59]
If the word "input" is used anywhere in a template, rendering any passed variables (local or context) fail.

I believe this stems from this commit, where you changed the word "data" to "input".

https://github.com/mauricemach/coffeekup/commit/03d0155d8770ba44ca22b5401f61e53840dc01cc

previously:

So I have a var called @person with a bunch of details, like "firstname" for instance.

If I use this code:
  p @person.firstname

The text correctly outputs the firstname. If I add a form in, like this:

  p @person.firstname
  form name: "input"

then I get an error:
  TypeError: Cannot read property 'firstname' of undefined
    at Function.<anonymous> (eval at <anonymous> (/home/hosting/checkoutly/code/node_modules/coffeekup/lib/coffeekup.js:303:12))
    at Object.anonymous (eval at <anonymous> (/home/hosting/checkoutly/code/node_modules/coffeekup/lib/coffeekup.js:303:12))

**Comment by mauricemach** [comment]
Duh! Reverted back to `data`.

Thing is, I'm expecting both data and options in this param, because that's how express rolls, so I wanted a less misleading name. But using an HTML element name was really _brilliant_ on my part.
