### ISSUE TITLE
html5 input required syntax

### ISSUE THREAD

**Issue by rdrey** [mauricemach/coffeekup#62]
Hey guys

this might be an issue with me not knowing coffeescript syntax properly yet (or coffeekup), but here's my question:

I'm playing with html5 forms (http://diveintohtml5.org/forms.html), and want to play with features like "required" in
<input id="q" required>

input id: 'q' #works fine
but how do I add a value-less parameter like "required"?

I've tried:
input id: 'q', required: '' # <- with an empty string
But coffeekup ignores the required parameter

Thanks for the help & coffeekup, coffeescript, mongoose, express, node are all blowing my mind!

**Comment by rdrey** [comment]
PS: How do I label the 'issue' as a question?

**Comment by rdrey** [comment]
Got it: 
    input id: 'q', required: true

outputs

`<input id="q" required="required">`
which works just like
`<input id="q" reguired>`

**Comment by mauricemach** [comment]
You could also use CoffeeScript's aliases to `true` like `on` and `yes`.

Another CoffeeScript trick would be `input {id: 'foo', required}`, which compiles to JS `input({id: 'foo', required: required})`. You could then feed the template a variable `required` with value `true`.

**Comment by rdrey** [comment]
Thanks, Maurice!

I found my solution by reading coffeekup's source, still getting used to all the different versions of 'true' ;) Thanks for the answer.

**Comment by mauricemach** [comment]
Anytime!
