### ISSUE TITLE
coffeekup.js missing from examples

### ISSUE THREAD

**Issue by kevingamble** [mauricemach/coffeekup#63]
The reference to coffeekup.js, in the "/examples/browser/creme" folder, points back to /lib, and the file does not exist there.

I have pulled the latest JS from the repo history (https://github.com/mauricemach/coffeekup/blob/c514d9b26bdc6e44709f624df00aff2275e60882/lib/coffeekup.js) and will try to use that, but just wanted to give a heads up that the ref is gone.

**Comment by kevingamble** [comment]
From using/downloading previous versions, a quick note about the existing index.html file.

Line 33/34 should be:
$('body').append CoffeeKup.render(codey, context: {stooges: stooges})

In the current file, it's missing the curly braces and throws an error.

**Comment by mauricemach** [comment]
To put the js at /lib, you have to run `cake build`. I should put this somewhere in the docs.

Didn't get your meaning regarding the index.html. The current line is:

```
$('body').append CoffeeKup.render(codey, stooges: stooges)
```

Which is written for 0.3.0beta, and works. In this version there's no need to put things inside `context`.

**Comment by kevingamble** [comment]
re: JS, gotcha. Thanks for that.

re: context; I was using your old 0.2.x JS file, so I had to keep it within the curly brackets. The cake file and upgrade to CK 0.3beta may make this point mute.

Thanks for the reply. Big fan of your work.

**Comment by mauricemach** [comment]
Hmmm got it. Yeah, the examples are supposed to be ran after `cake build`. I added a note to the readme. Thanks for the feedback!

BTW, the mailing list and IRC channel are up (see readme). Hoping to see you there!
