### ISSUE TITLE
self closing / obsolete tags

### ISSUE THREAD

**Issue by aeosynth** [mauricemach/coffeekup#66]
hello, I'm playing around with a [ck rewrite](https://github.com/aeosynth/ck/blob/rewrite/ck.coffee), and I wanted to get everything correct this time so I went looking at the official sources. my results:

[void (self closing)](http://www.w3.org/TR/html5-author/syntax.html#void-elements)

> area base br col command embed hr img input keygen link meta param source track wbr

[complete set of elements](http://www.w3.org/TR/html-markup/elements.html#elements), minus self closing

> a abbr address article aside audio b bdi bdo blockquote body button canvas caption cite code colgroup datalist dd del details dfn div dl dt em fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hgroup html i iframe ins kbd label legend li map mark menu meter nav noscript object ol optgroup option output p pre progress q rp rt ruby s samp script section select small span strong style sub summary sup table tbody td textarea tfoot th thead time title tr u ul var video

[obsolete](http://www.w3.org/TR/html5-author/obsolete.html#non-conforming-features)

> applet acronym bgsound dir frame frameset noframes isindex listing nextid noembed plaintext rb strike xmp basefont big blink center font marquee multicol nobr spacer tt

**Comment by mauricemach** [comment]
I like your style. CK is mercilessly minimal and very inspiring.

I should have done this element shopping at the reference a long time ago. Thanks for the push.

The `var` element obviously couldn't be included. We'll have to fallback to `tag` or `text` with this sucker. Maybe I'll implement a similarly-looking replacement for it in the future (`v4r` anyone? :))

**Comment by aeosynth** [comment]
Thanks for the compliment :). I only add things when I actually need them; if I were publishing on npm, I'd have to add a bit more.

btw, I see the source for [coffeekup.html](https://github.com/mauricemach/coffeekup/blob/master/docs/coffeekup.html), where can I find page online?

**Comment by mauricemach** [comment]
It's not at the website yet... I gotta revamp it.
