### ISSUE TITLE
indexOf not supported in IE7

### ISSUE THREAD

**Issue by jaekwon** [mauricemach/coffeekup#71]
It looks like coffeekup isn't compatible with IE7 because indexOf isn't defined in Array.prototype. 
I don't personally care, i can work around this issue. Is there a recommended script I can import to define some of these common functions for IE (and maybe other browsers)?

**Comment by mauricemach** [comment]
Sorry, I should have been using CoffeeScript's `in` operator for arrays. Fixed in master.

Feel free to reopen the issue if necessary.
