### ISSUE TITLE
why is the cache turned off by default?

### ISSUE THREAD

**Issue by jaekwon** [mauricemach/coffeekup#72]
I'm using coffeekup on the client from a django project. I noticed that IE7 was slow to render a list of widgets, and noticed that turning on caching helped. Is there a reason why caching is off by default? There was nothing noted on the README file. #question

**Comment by mauricemach** [comment]
Caching is an optimization and prevents templates from being recompiled, which is something we want in production but not in development, most of the time. And development mode is also usually the default.

Yeah, I should put a link to /docs/reference.md on the README and the website. This is where the options are documented.
