### ISSUE TITLE
Date() parser

### ISSUE THREAD

**Issue by kevingamble** [mauricemach/coffeekup#76]
I have searched around, tried several different methods in both coffeescript and native JS, and there doesn't seem to be any way to natively parse a date object (JSON, for example) in CoffeeKup.

As the most basic example, here is what I have, which fails to return a parsed date, instead, it returns today's date/time:
dt = Date(parseInt(@feed[i].CreatedOn.substring(6,24)))

Has anyone used any date() objects in CoffeeKup?

**Comment by mauricemach** [comment]
CoffeeKup has nothing to do with `Date`, it's a JavaScript object, with docs available [here](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date).

If you instantiate `Date`, I think it should work: `new Date(yourstring)`.
