### ISSUE TITLE
Attaching event handlers directly

### ISSUE THREAD

**Issue by smathy** [mauricemach/coffeekup#79]
It'd be great to be able to do this:

```
button "foo", "Foo", onclick: ->
  get "/foo"
```

Instead of having to attach it in the onload.

**Comment by mauricemach** [comment]
Thanks (for moving the issue)!

I'm thinking of rendering it as `onclick="(function(){foo();}).call(this)"`, which is the default CoffeeScript wrapping. What do you think?

**Comment by smathy** [comment]
Yeah, makes sense.
