### ISSUE TITLE
how to render namespaced HTML entities

### ISSUE THREAD

**Issue by flippyhead** [mauricemach/coffeekup#8]
How should I write coffeekup scripts to render unusual html entities, such as the Facebook Connect button?

fb:login-button/fb:login-button

**Comment by mauricemach** [comment]
CoffeeKup is focused on HTML, but you can also render any arbitrary element using the `tag` function:

```
puts ck.render -> tag 'fb:login-button'
=> '<fb:login-button></fb:login-button>'
```

You can also create a shortcut for it and name it whatever you like:

```
template = ->
  login_button 'foo'

login_button = (args) ->
  tag 'fb:login-button', args

puts ck.render template, locals: {login_button: login_button}
=> <fb:login-button>foo</fb:login-button>
```
