### ISSUE TITLE
Conditional IE styles?

### ISSUE THREAD

**Issue by randallb** [mauricemach/coffeekup#80]
I know you could escape / heredoc ie tags, but I thought coffeekup supported IE specific style syntax... am I crazy? If it does support it, probably needs to be better documented (couldn't find on coffeekup.org / the readme markdown). Thx!

**Comment by randallb** [comment]
I'm a moron. Found it in the docs.

**Comment by mauricemach** [comment]
:) no problem

**Comment by nbartlomiej** [comment]
Answering this question anyway for search engine visitors (like me):

### Other locals

#### ie

Writes an IE conditional comment. Ex.:

```
ie 'gte IE8', ->
  link href: 'ie.css', rel: 'stylesheet'

<!--[if gte IE8]>
  <link href="ie.css" rel="stylesheet" />
<![endif]-->
```

Taken from: https://github.com/mauricemach/coffeekup/blob/master/docs/reference.md
