### ISSUE TITLE
Echoing out template vars into embedded coffeescript?

### ISSUE THREAD

**Issue by randallb** [mauricemach/coffeekup#81]
So I'm using an embedded coffeescript block. I get that when I'm normally using templating, I can just use @blah, etc., but in this template block, it's going to be interpreted as part of the embedded coffeescript.

How do I echo out template vars into the embedded coffeescript tag?

**Comment by mauricemach** [comment]
Since it's not a string, you can't. My suggestion would be to use `script str` to set these variables:

``` coffeescript
script "window.stuff = {foo: #{foo}, bar: #{bar}}"
coffeescript -> console.log stuff.foo
```
